search/config/urls.py
from django.contrib import admin
from django.urls import path, include
from naver.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("naver/", include("naver.urls")),
    path("daum/", include("daum.urls")),
    # http://127.0.0.1:8000/
    path("", index, name="index"),
]

search/daum/urls.py
from django.urls import path
from .views import daum


app_name = "daum"

urlpatterns = [
    # http://127.0.0.1:8000/daum
    path("", daum, name="daum"),
]

search/naver/urls.py
from django.urls import path
from .views import naver


app_name = "naver"

urlpatterns = [
    # http://127.0.0.1:8000/naver
    path("", naver, name="naver"),
]

search/daum/models.py
from django.db import models


# Create your models here.
class DaumData(models.Model):
    title = models.CharField(max_length=300)
    link = models.URLField()
    specific_id = models.CharField(max_length=15, null=True)

    # admin계정에서 바로 제목으로 볼수있게
    def __str__(self):
        return self.title

search/naver/models.py
from django.db import models


# Create your models here.
class NaverData(models.Model):
    title = models.CharField(max_length=300)
    link = models.URLField()
    specific_id = models.CharField(max_length=15, null=True)

    # admin계정에서 바로 제목으로 볼수있게
    def __str__(self):
        return self.title

search/daum/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import DaumData


# Create your views here.
def daum(request):
    daum = DaumData.objects.all()
    context = {"daum": daum}
    # 정보를 전달
    return render(request, "daum.html", context)

search/naver/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import NaverData


# Create your views here.
def naver(request):
    naver = NaverData.objects.all()
    context = {"naver": naver}
    # 정보를 전달
    return render(request, "naver.html", context)


# 홈화면
def index(request):
    # index.html 템플릿
    return render(request, "index.html")

search/templates/daum.html
{% extends 'index.html' %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <title>다음 뉴스 "파이썬" 검색결과</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </head>

  {% block contents %}

    <body>
      <div class="container">
        <table class="table table-striped">
          <thead>
            <tr>
              <td>
                <b></b>
              </td>
              <td>
                <b>기사 제목</b>
              </td>
              <td>
                <b>링크</b>
              </td>
            </tr>
          </thead>
          <tbody>
            {% for daum in daum %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ daum.title }}</td>
                <td>
                  <a href="{{ daum.link }}" target="_blank">{{ daum.link }}</a>
                </td>
              </tr>
            {% endfor %}
            <tbody></table>
          </body>
        {% endblock contents %}

search/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block style %}{% endblock style %}
  </head>

  <body>
    {% include 'navbar.html' %}
    <div style="text-align: center;">
      <h2>"파이썬" 검색결과 (1~10page)</h2>
    </div>
    <div class="container">
      {% block contents %}{% endblock contents %}
    </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock script %}
  </body>

</html>

search/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" aria-current="page" href="{% url 'naver:naver' %}">네이버뉴스</a>
        <a class="nav-link" aria-current="page" href="{% url 'daum:daum' %}">다음뉴스</a>
      </div>
    </div>
  </div>
</nav>

search/templates/naver.html
{% extends 'index.html' %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <title>네이버 뉴스 "파이썬" 검색결과</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </head>

  {% block contents %}

    <body>
      <div class="container">
        <table class="table table-striped">
          <thead>
            <tr>
              <td>
                <b></b>
              </td>
              <td>
                <b>기사 제목</b>
              </td>
              <td>
                <b>링크</b>
              </td>
            </tr>
          </thead>
          <tbody>
            {% for naver in naver %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ naver.title }}</td>
                <td>
                  <a href="{{ naver.link }}" target="_blank">{{ naver.link }}</a>
                </td>
              </tr>
            {% endfor %}
            <tbody></table>
          </body>
        {% endblock contents %}